### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by feiercrack** [captn-nick/MSFS-Mod-Selector#1]
not working at all!
never saw the ui.

started it from the command line, sort out the corrupted folders.

edited the mods.txt with "AP\NA\AL\airport-2S1-quelcertoleo-vashon\vashon"

(tried also with an zipfile airport-2S1-quelcertoleo-vashon\vashon.zip)

i have an unzipped folder called >"airport-2S1-quelcertoleo-vashon" in the temp folder.
then i got some errors in cmd line:
D:\D-Games\MSFlightSim2020>java -jar MsfsModSelector.jar
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
        at org.codehaus.groovy.runtime.BytecodeInterface8.objectArrayGet(BytecodeInterface8.java:363)
        at msfsmodmanager.state.Mods$_loadRegisteredMods_closure2.doCall(Mods.groovy:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:442)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3170)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3140)
        at msfsmodmanager.state.Mods.loadRegisteredMods(Mods.groovy:14)
        at msfsmodmanager.Main.init(Main.groovy:18)
        at msfsmodmanager.Main.main(Main.groovy:12)

wow, very groovy...

please be more precisely with an example what exactly has to be written in there!
and should the addons be "zipped" or unzipped before adding them into the temp folder?
then where exactly and how to use the "Deactivate all" function? from cmd line, or the ui, where?

an addon with different aircrafts would be nice also...

**Comment by captn-nick** [comment]
Thanks for your feedback.

Feel free to try out the new [release 0.2](https://github.com/captn-nick/MSFS-Mod-Selector/releases/tag/0.2) now.

I have also added a few examples of how a mods.txt entry should look like in the [README.me](https://github.com/captn-nick/MSFS-Mod-Selector). I think you simply need to replace the ```\``` with tab spaces, but just to be sure, check again with the examples.

Also, yes, only works with unzipped mods.

"Deactivate all" will be on the UI.

I'll think about an additional mod type called "aircrafts".

**Comment by feiercrack** [comment]
v0.2 opens up the UI with message: !!! Found unregistered mods:
then i have to click the "ok" button
after that, UI quits. 
Dont know what to do next, so i choose ur v0.3

v0.3 doesnt open up the UI.
i tried then via cmd line:
Error:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at msfsmodmanager.state.Mods.loadRegisteredMods(Mods.groovy:22)
        at msfsmodmanager.Main.init(Main.groovy:26)
        at msfsmodmanager.Main.main(Main.groovy:19)

Addition:
i use the ms-store/game pass standard version, so my "Community" folder with all mods  is here --> D:\D-Games\MSFlightSim2020\Community
I dont have that "Package" folder in that tree. Only in C:\Users\user\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community

but this folder is empty and i dont use that on my C: drive!

**Comment by captn-nick** [comment]
"!!! Found unregistered mods" means you have to manually register all the listed mods in your mods.txt file, as explained in the [README](https://github.com/captn-nick/MSFS-Mod-Selector#adding-a-mod).

Could it be that your mods.txt file is empty? It doesn't work with an empty mods.txt file.

If not, can you please copy/paste the full content of your mods.txt file here?

Also, please try it with the new v. 0.4.

**Comment by feiercrack** [comment]
yeah... thats quite time consumpting to play around with your java script.

finally i made it to run for the first time.

**my fault was to remove the \t  and exchange it with "tab"**

i have added WA - Washington State to the config.properties, cause my testfile airport-2S1-vashon-quelcertoleo  is from there.
if i got time, i do some more testings.
i have around 600 addons, and i dont like to insert each one per hand! there should be some kinda automation..
anyway, thanks!

**Comment by captn-nick** [comment]
Thanks for your interest.

Of course, automation will come with a future version. This project is still early beta. Please feel free to check out its progress later!
