### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by thommy2403** [captn-nick/MSFS-Mod-Selector#2]
msfsmodmanager.ex.ModsParseException$LineParseException: Cannot read line 1 in mods.txt:
AP\tEU\tUK\torbx-airport-egnm-leeds-bradford\tEGNM ## Airport Leeds Bradford
	at msfsmodmanager.state.Mods$_loadRegisteredMods_closure3.doCall(Mods.groovy:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at org.codehaus.groovy.runtime.metaclass.TransformMetaMethod.invoke(TransformMetaMethod.java:57)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass$1.invoke(ClosureMetaClass.java:281)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3170)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3140)
	at msfsmodmanager.state.Mods.loadRegisteredMods(Mods.groovy:26)
	at msfsmodmanager.Main.init(Main.groovy:38)
	at msfsmodmanager.Main.restart(Main.groovy:31)
	at msfsmodmanager.Main.start(Main.groovy:27)
	at msfsmodmanager.Main.main(Main.groovy:15)
Caused by: msfsmodmanager.ex.ModsParseException$MissingDataForLineParseException: Cannot read "mod name" information for line 1 in mods.txt:
AP\tEU\tUK\torbx-airport-egnm-leeds-bradford\tEGNM ## Airport Leeds Bradford
	at msfsmodmanager.state.Mods.parseLine(Mods.groovy:75)
	at msfsmodmanager.state.Mods.access$1(Mods.groovy)
	at msfsmodmanager.state.Mods$_loadRegisteredMods_closure3.doCall(Mods.groovy:33)
	... 19 more

**Comment by captn-nick** [comment]
Hi. Thanks for opening an issue here.

You need to replace "\t" with actual tab spaces.

I have updated the [README](https://github.com/captn-nick/MSFS-Mod-Selector#adding-a-mod) accordingly to make this more clear.

Note that you can now also find a complete mods.txt file [here](https://github.com/captn-nick/MSFS-Mod-Selector/blob/master/external-test-resources/mods.txt) (example mods only) and [here](https://github.com/captn-nick/MSFS-Mod-Repository/blob/master/mods-db.txt) (actual flightsim.to mods)

**Comment by frankenstein2020** [comment]
Hi, 

that's my error001 message I get when I try to start msfsmodselector.jar

Any help there?

**Microsoft Windows [Version 10.0.19041.572]
(c) 2020 Microsoft Corporation. Alle Rechte vorbehalten.

H:\WpSystem\S-1-5-21-2984540516-3285555584-4000325122-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe>java -jar msfsmodselector.jar
Error.001
!!! Unexpected error occurred.
If you believe this is a bug, please report it on the project's GitHub page (https://github.com/captn-nick/MSFS-Mod-Selector/issues)
with the following information. Make sure to read the README (https://github.com/captn-nick/MSFS-Mod-Selector) first.
java.io.FileNotFoundException: H:\WpSystem\S-1-5-21-2**984540516-3285555584-4000325122-1001\AppData\Local\Packages\Community
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.checkDir(ResourceGroovyMethods.java:1043)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFile(ResourceGroovyMethods.java:1062)
        at msfsmodmanager.state.Mods.findAllMods(Mods.groovy:105)
        at msfsmodmanager.Main.init(Main.groovy:71)
        at msfsmodmanager.Main.restart(Main.groovy:36)
        at msfsmodmanager.Main.start(Main.groovy:32)
        at msfsmodmanager.Main.main(Main.groovy:20)

**Comment by captn-nick** [comment]
@frankenstein2020 Hi, please **do not** "hijack" other people's tickets. Please open up your own ticket. Otherwise I cannot help you.

**Comment by frankenstein2020** [comment]
Sorry, 
I'm brand new in here and thought I could write to that topic.

But if you've got a problem with me, just delete my account. I don't care.

**Comment by captn-nick** [comment]
@frankenstein2020 Please open a new issue here: https://github.com/captn-nick/MSFS-Mod-Selector/issues/new and I will gladly help you.
