### ISSUE TITLE
Error.001

### ISSUE THREAD

**Issue by johnwillimas** [captn-nick/MSFS-Mod-Selector#4]
When I run the current version (0.9) the programme builds the database and I then get an error.001 with the below data. ....

java.io.FileNotFoundException: C:\Users\jcw\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\MSFS Mod Selector\Community
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.checkDir(ResourceGroovyMethods.java:1043)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.eachFile(ResourceGroovyMethods.java:1062)
	at msfsmodmanager.state.Mods.findAllMods(Mods.groovy:155)
	at msfsmodmanager.Main.init(Main.groovy:79)
	at msfsmodmanager.Main.restart(Main.groovy:42)
	at msfsmodmanager.Main.start(Main.groovy:38)
	at msfsmodmanager.Main.main(Main.groovy:26)

**Comment by captn-nick** [comment]
Hi. I believe you have unzipped the program in the wrong folder.

You have to unzip it directly into the C:\Users\jcw\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\ folder, not in a "...\MSFS Mod Selector" subfolder.

In other words: Unzip it directly into the parent directory of your Community folder (the one which contains al the mods).

[Details](https://github.com/captn-nick/MSFS-Mod-Selector#setup)

**Comment by johnwillimas** [comment]
Yepp, that was it thanks.
